### ISSUE TITLE
Update to upstream v0.27.2

### ISSUE THREAD

**Issue by RoonMoonlight** [NewPipeX/NewPipeX#46]
### Checklist

- [X] I made sure that there are *no feature requests* - [open](https://github.com/NewPipeX/NewPipeX/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22) or [closed](https://github.com/NewPipeX/NewPipeX/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22) - that already cover my request.
- [X] My feature request has a well-defined scope and is described in sufficient detail.
- [X] I have read and understood the [contribution guidelines](https://github.com/NewPipeX/NewPipeX/blob/main/.github/CONTRIBUTING.md).

### Feature description

No more suffering. Upstream has just released 0.27.2 update today and now available. Would be cool if this client can be updated to upstream 0.27.2

### Why do you want this feature?

It fixes most of 403 error present in previous version.

**Comment by javulticat** [comment]
Thanks for the ping! [`v0.27.2-1` of **NewPipe X** is now available](https://github.com/NewPipeX/NewPipeX/releases/tag/v0.27.2-1).
